#
FROM muccg/bpaworkflow-builder
MAINTAINER https://github.com/muccg/bpaworkflow

#At build time changing these args allow us to use a local devpi mirror
# Unchanged, these defaults allow pip to behave as noremal
ARG ARG_PIP_INDEX_URL="https://pypi.python.org/simple"
ARG ARG_PIP_TRUSTED_HOST="127.0.0.1"

# Runtime args, don't re-use build time args
ENV PRODUCTION 0
ENV DEBUG 1
ENV PIP_INDEX_URL $ARG_PIP_INDEX_URL
ENV PIP_TRUSTED_HOST $ARG_PIP_TRUSTED_HOST
ENV NO_PROXY ${PIP_TRUSTED_HOST}

# Strictly speaking not needed as we mount over the top
# However let's make it explicit that we don't want /app from the build image
RUN rm -rf /app && mkdir -p /app

# # For dev we use root so we can shell in and do evil things
USER root
WORKDIR /app

RUN env | sort

# Add our python deps in multiple docker layers
# hgvs was failing due to lack of nose, hence the order
RUN pip install 'git+ssh://git@bpaingest/muccg/bpa-ingest.git@4.0.1#egg=bpa-ingest'
COPY ./requirements/dev-requirements.txt /app/bpaworkflow/
RUN pip install --upgrade -r bpaworkflow/dev-requirements.txt
COPY ./requirements/test-requirements.txt /app/bpaworkflow/
RUN pip install --upgrade -r bpaworkflow/test-requirements.txt
COPY ./requirements/runtime-requirements.txt /app/bpaworkflow/
RUN pip install --upgrade -r bpaworkflow/runtime-requirements.txt

# Copy code and install the app
COPY . /app
RUN pip ${PIP_OPTS} install --upgrade -e bpaworkflow

EXPOSE 8000 9000 9001 9100 9101
VOLUME ["/app", "/data"]

ENV HOME /data
WORKDIR /data

# entrypoint shell script that by default starts runserver
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["runserver_plus"]
