# bpaworkflow production
FROM bioplatformsaustralia/bpaworkflow-base
MAINTAINER https://github.com/bioplatformsaustralia/bpaworkflow

ARG ARG_BUILD_VERSION

ENV BUILD_VERSION $ARG_BUILD_VERSION

RUN env | sort

RUN mkdir -p /data \
    && /bin/chown bioplatforms:bioplatforms /data

ADD build/${PROJECT_NAME}-${BUILD_VERSION}.tar.gz /

EXPOSE 9100 9101
VOLUME ["/data"]


# uwsgi user runs under www-data
RUN usermod -a -G bioplatforms www-data
RUN chown -R bioplatforms:bioplatforms /data
RUN chmod 0775 /data
# Drop privileges, set home
USER bioplatforms
ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["gunicorn"]
