#
FROM bioplatformsaustralia/bpaworkflow-builder
MAINTAINER https://github.com/bioplatformsaustralia/bpaworkflow

# Runtime args, don't re-use build time args
ENV PRODUCTION 0
ENV DEBUG 1

# Strictly speaking not needed as we mount over the top
# However let's make it explicit that we don't want /app from the build image
RUN rm -rf /app && mkdir -p /app

# # For dev we use root so we can shell in and do evil things
USER root
WORKDIR /app

RUN env | sort

# Copy code and install the app
COPY . /app
RUN cd /app/bpaworkflow && poetry install

EXPOSE 8000 9000 9001 9100 9101
VOLUME ["/app", "/data"]

ENV HOME /data
WORKDIR /data

# entrypoint shell script that by default starts runserver
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["gunicorn"]
