# Generated by Django 3.0.6 on 2020-05-12 02:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(db_index=True, max_length=36)),
                ("submitted", models.DateTimeField(auto_now=True)),
                ("importer", models.TextField()),
                ("xlsx_name", models.TextField()),
                ("xlsx_data", models.BinaryField(null=True)),
                ("md5_name", models.TextField()),
                ("md5_data", models.BinaryField(null=True)),
                ("state", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
